# conda env create -f environment.yml
name: h5coro
channels:
  - conda-forge
dependencies:
  - boto3
  - earthaccess
  - h5py
  - ipykernel
  - jupyterlab
  - jupyterlab_widgets
  - numpy
  - matplotlib
  - python>=3.10,<=3.12.0  # newer versions changed fork-in-multithreaded process behavior
  - pip
  - pytest
  - requests
  - s3fs
  - xarray